name: Java CI with Gradle

on:
  push:
    branches:
      - env-values
  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.RAPIDAPI_KEY }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.RAPIDAPI_KEY}} | sed 's/./& /g' 

      - name: Run REST Assured & Cucumber tests
        run: gradle testsCucumber -Dcucumber.options="--tags @Brave"

      - name: Run REST Assured & TestNG tests
        run: gradle test

      - name: Upload REST Assured & Cucumber report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: REST Assured & Cucumber report
          path: test-output/HtmlReport

      - name: Upload REST Assured & TestNG report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: REST Assured & TestNG report
          path: build/reports/tests/test
