name: Java CI with Gradle

on:
 push:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build project
      run: gradle build

    - name: Run cucumber tests
      run: gradle test -Dcucumber.options="--tags @API"

    - name: Upload report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ExtentHtml
        path: test-output/HtmlReport/ExtentHtml.html